// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	FullName  sql.NullString `json:"full_name"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
